#!/usr/bin/env node

import { spawnSync } from 'node:child_process';
import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { dirname, isAbsolute, join, normalize, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const templateRoot = dirname(fileURLToPath(import.meta.url));
const sourceCliDir = join(templateRoot, 'template', 'submodule-governance', 'cli');

function usage() {
  console.log(`Usage:
  node bootstrap.mjs [target_repo_path] [--strict]

Examples:
  node bootstrap.mjs .
  node bootstrap.mjs /path/to/main-repo
  node bootstrap.mjs /path/to/main-repo --strict`);
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd,
    encoding: 'utf8',
    stdio: options.inherit ? 'inherit' : 'pipe',
    env: { ...process.env, ...(options.env || {}) },
  });
  if (!options.allowFailure && result.status !== 0) {
    const detail = [result.stdout, result.stderr].filter(Boolean).join('\n').trim();
    throw new Error(`${command} ${args.join(' ')} failed${detail ? `\n${detail}` : ''}`);
  }
  return result;
}

function out(command, args, options = {}) {
  return (run(command, args, options).stdout || '').trim();
}

function git(args, options = {}) {
  return run('git', args, options);
}

function gitOut(args, options = {}) {
  return out('git', args, options);
}

function absoluteFrom(root, value) {
  return isAbsolute(value) ? normalize(value) : normalize(join(root, value));
}

function parseArgs(argv) {
  let targetRepo = '';
  let strict = false;
  for (const arg of argv) {
    if (arg === '--strict') strict = true;
    else if (arg === '-h' || arg === '--help') {
      usage();
      process.exit(0);
    } else if (!targetRepo) targetRepo = arg;
    else throw new Error(`Unexpected argument: ${arg}`);
  }
  return { targetRepo: targetRepo || process.cwd(), strict };
}

function writeLauncher(file, targetFile) {
  writeFileSync(
    file,
    `#!/usr/bin/env node
import { spawnSync, execFileSync } from 'node:child_process';
import { isAbsolute, join } from 'node:path';

const repoRoot = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
let gitDir = execFileSync('git', ['rev-parse', '--git-dir'], { cwd: repoRoot, encoding: 'utf8' }).trim();
if (!isAbsolute(gitDir)) gitDir = join(repoRoot, gitDir);

const target = join(gitDir, 'submodule-governance', 'cli', '${targetFile}');
const result = spawnSync(process.execPath, [target, ...process.argv.slice(2)], {
  cwd: repoRoot,
  stdio: 'inherit',
  env: process.env,
});
process.exit(result.status ?? 1);
`,
  );
  chmodSync(file, 0o755);
}

function ensureExclude(targetRepo) {
  const excludeFile = absoluteFrom(targetRepo, gitOut(['rev-parse', '--git-path', 'info/exclude'], { cwd: targetRepo }));
  mkdirSync(dirname(excludeFile), { recursive: true });
  if (!existsSync(excludeFile)) writeFileSync(excludeFile, '');
  const existing = readFileSync(excludeFile, 'utf8');
  if (!/^\.submodule-governance\/$/m.test(existing)) {
    writeFileSync(
      excludeFile,
      `${existing}${existing.endsWith('\n') || existing.length === 0 ? '' : '\n'}\n# Local launcher generated by submodule-governance bootstrap.\n.submodule-governance/\n`,
    );
  }
}

function writeConfig(targetRepo, strict) {
  const configFile = join(targetRepo, '.submodule-governance.config');
  const strictValue = strict ? 'true' : 'false';
  if (!existsSync(configFile)) {
    writeFileSync(
      configFile,
      `[governance]
    # false: only warn when submodule HEAD is not pushed to upstream.
    # true: fail and block push when submodule HEAD is not pushed to upstream.
    requirePushed = ${strictValue}
    # mainBranch = main

# 子模块分支配置示例。subsection 名称必须与 .gitmodules 中的路径一致。
# [submodule "ios"]
#     branch = dev/v2.2.7/stable
#
# [submodule "android"]
#     branch = dev/v2.2.7/stable
`,
    );
    return;
  }

  git(['config', '--file', configFile, '--list'], { cwd: targetRepo });
  git(['config', '--file', configFile, 'governance.requirePushed', strictValue], { cwd: targetRepo });
}

function install({ targetRepo, strict }) {
  targetRepo = resolve(targetRepo);
  git(['-C', targetRepo, 'rev-parse', '--show-toplevel']);
  targetRepo = gitOut(['-C', targetRepo, 'rev-parse', '--show-toplevel']);
  const gitDir = absoluteFrom(targetRepo, gitOut(['-C', targetRepo, 'rev-parse', '--git-dir']));
  const toolDir = join(gitDir, 'submodule-governance');
  const cliDir = join(toolDir, 'cli');
  const entryDir = join(targetRepo, '.submodule-governance');
  const entryCliDir = join(entryDir, 'cli');

  mkdirSync(cliDir, { recursive: true });
  mkdirSync(entryCliDir, { recursive: true });

  for (const file of ['submodule-governance.mjs', 'submodule-governance-mcp.mjs']) {
    copyFileSync(join(sourceCliDir, file), join(cliDir, file));
    chmodSync(join(cliDir, file), 0o755);
  }

  writeFileSync(
    join(entryDir, '.generated-by-submodule-governance'),
    'This directory contains local Node launcher wrappers generated by submodule-governance bootstrap.\nIt is safe to delete and recreate by running bootstrap.mjs again.\n',
  );
  writeLauncher(join(entryCliDir, 'submodule-governance.mjs'), 'submodule-governance.mjs');
  writeLauncher(join(entryCliDir, 'submodule-governance-mcp.mjs'), 'submodule-governance-mcp.mjs');

  ensureExclude(targetRepo);
  writeConfig(targetRepo, strict);

  run('node', [join(cliDir, 'submodule-governance.mjs'), 'install-hooks'], { cwd: targetRepo, inherit: true });
  console.log('Running initial check...');
  run('node', [join(cliDir, 'submodule-governance.mjs'), 'check'], {
    cwd: targetRepo,
    allowFailure: true,
    inherit: true,
    env: { SUBMODULE_INTERACTIVE: '0' },
  });

  console.log('Bootstrap complete.');
  console.log(`Target repo: ${targetRepo}`);
  console.log(`Tool dir: ${toolDir}`);
  console.log(`Launcher dir: ${entryDir}`);
  console.log('Use launcher commands from the worktree root, for example:');
  console.log('  node .submodule-governance/cli/submodule-governance.mjs check');
  console.log('  node .submodule-governance/cli/submodule-governance.mjs fix');
  console.log('  node .submodule-governance/cli/submodule-governance.mjs status --json');
  console.log(`Mode: ${strict ? 'strict (governance.requirePushed=true)' : 'non-strict (governance.requirePushed=false)'}`);
}

try {
  install(parseArgs(process.argv.slice(2)));
} catch (error) {
  console.error(error.message || String(error));
  process.exitCode = 1;
}
